use db_coursework;
create table c(S_No char(3) not null,S_name nvarchar(50) not null,transfer int not null,
                   attraction nvarchar(50) default null, PRIMARY KEY(S_name));

insert C values('C01','安河桥北',0,null);
insert C values('C02','北宫门',0,'颐和园');
insert C values('C03','西苑',0,null);
insert C values('C04','圆明园',0,'圆明园');
insert C values('C05','北京大学东门',0,null);
insert C values('C06','中关村',0,null);
insert C values('C07','海淀黄庄',1,null);
insert C values('C08','人民大学',0,null);
insert C values('C09','魏公村',0,null);
insert C values('C10','国家图书馆',1,'国家图书馆');
insert C values('C11','动物园',0,'动物园');
insert C values('C12','西直门',1,null);
insert C values('C13','新街口',0,null);
insert C values('C14','平安里',1,null);
insert C values('C15','西四',0,null);
insert C values('C16','灵境胡同',0,null);
insert C values('C17','西单',1,null);
insert C values('C18','宣武门',1,null);
insert C values('C19','菜市口',1,null);
insert C values('C20','陶然亭',0,null);
insert C values('C21','北京南站',1,null);
insert C values('C22','马家堡',0,null);
insert C values('C23','角门西',1,null);
insert C values('C24','公益西桥',0,null);
insert C values('C25','新宫',0,null);
insert C values('C26','西红门',0,null);
insert C values('C27','高米店北',0,null);
insert C values('C28','高米店南',0,null);
insert C values('C29','枣园',0,null);
insert C values('C30','清源路',0,null);
insert C values('C31','黄村西大街',0,null);
insert C values('C32','黄村火车站',0,null);
insert C values('C33','义和庄',0,null);
insert C values('C34','生物医药基地',0,null);
insert C values('C35','天宫院',0,null);
